---
title: ""
---

## Working Papers

- [Trade Shocks and Human Capital: Evidence from Brazil's Trade Liberalization](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4844234)
<small> (with [Marcos Nakaguma](https://sites.google.com/view/nakaguma/home)) </small> <br>
<small> Revise & Resubmit <em>Journal of International Economics</em> </small> <br>

- [How Immigration Shapes Politics: Populism, Labor Movements, and Political Preferences in Brazil](/files/papers/immigration.pdf)
<small> (with [Marcos Nakaguma](https://sites.google.com/view/nakaguma/home) and [Thales Pereira](https://thaleszp.com/)) </small> 

- [Fiscal Capacity and the Provision of Public Goods in Brazil, 1891-1930](/files/papers/fiscal_capacity.pdf)

## Work in Progress

- Sugarcane Expansion and Development: Evidence from São Paulo 
<small> (with Yuri Luz and [Marcos Nakaguma](https://sites.google.com/view/nakaguma/home)) </small> 

- Railroad Expansion and Mortality in Early Twentieth-Century Brazil
<small> (with [Darcio Genicolo](https://darciogm.github.io/)) </small>

- Broadcasting Populism: Radio and Mass Politics in Brazil

- Political Power and State Capacity in Early Twentieth-Century Brazil
