---
title: ""
---

<p style="text-align: center; margin-bottom: 0; font-size: 24px;">
**EAE1106 - Métodos Computacionais para Economia**
</p>

<p style="text-align: center; margin-bottom: 0;">
Faculdade de Economia, Administração, Contabilidade e Atuária<br>
Universidade de São Paulo
</p>
<p style="text-align: center; margin-top: 5px;">
1º semestre de 2026
</p>

---

**Professor**: Arthur Viaro<br>
**Atendimento**: Sala 230, FEA 2. [Link](https://calendar.app.google/iX1vNsRk9BTEQpnd9) para agendamento.<br><br>
**Aulas**: Laboratório 312, FEA 5<br>
Turma 121 - ter 19:30-21:10 / qui 21:20-23:00<br>
Turma 122 - ter 21:20-23:00 / qui 19:30-21:10<br>

Clique [aqui](sta199-summer-1-syllabus.pdf) para baixar o programa em PDF.

## Descrição

<div style="text-align: justify;">
A disciplina tem o objetivo de introduzir os estudantes ao raciocínio computacional, aos conceitos relevantes de computação, e às suas aplicações para resolver problemas relevantes no campo da Economia. Para tanto, o curso utilizará a linguagem Python, amplamente utilizada em diversas áreas das ciências. Espera-se que ao final do curso o estudante tenha, além do domínio sobre a sintaxe da linguagem utilizada no curso, capacidade de formular e resolver problemas utilizando recursos computacionais.
</div>

## Programa do Curso

1. Fundamentos da Computação e Algoritmos
2. Introdução ao Python
3. Tipos de Dados e Expressões
4. Controle de Fluxo e Iteração
5. Funções
6. Programação Orientada a Objetos
7. Aplicações I: Dados
8. Aplicações II: Visualização de Dados
9. Introdução ao R

Consulte o cronograma detalhado (*sujeito a alterações*): [Plano de aulas](/teaching/eae1106/cronograma.qmd)

## Critérios de Avaliação

<div style="text-align: justify;">
A avaliação da disciplina será composta por:

| Atividade           | Peso    | Detalhes                                   |
| :------------------ | :------ | :----------------------------------------- |
| Lista de exercícios | 20%     | Entregas individuais via Moodle            |
| Prova intermediária | 30%     | Avaliação individual em sala de aula       |
| Trabalho final      | 50%     | Projeto aplicado em grupo (máx. 5 pessoas) |

O trabalho final consistirá em um projeto aplicado de análise de dados, a ser desenvolvido em grupo e entregue ao final do semestre. Os estudantes que não alcançarem média final igual ou superior a 5,0 deverão realizar prova de reavaliação, conforme previsto no regimento da faculdade.

Os grupos deverão ter no máximo 5 alunos e deverão ser **informados até o dia 15/abr**. As instruções detalhadas para a elaboração do trabalho serão divulgadas nessa mesma data. O relatório final **deverá ser entregue em formato PDF, até às 23h59 do dia 10/jun**, exclusivamente por meio do sistema Moodle. A avaliação do trabalho ocorrerá durante as apresentações, que serão realizadas nos dois últimos encontros do semestre, conforme previsto no plano de aulas. Cada grupo terá 20 minutos para a apresentação e TODOS os membros do grupo devem estar presentes. **O membro do grupo que não comparecer à aula de apresentação terá sua nota zerada**.

</div>

## Horário de Atendimento

<div style="text-align: justify;">
Os atendimentos podem ser agendados por meio do [link de agendamento](https://calendar.app.google/iX1vNsRk9BTEQpnd9). O agendamento prévio não é obrigatório, mas é recomendado. Caso mais de uma pessoa procure atendimento no mesmo horário, terá prioridade quem tiver feito o agendamento antecipadamente. Além disso, o agendamento evita desencontros e garante que o professor estará disponível no momento da chegada do aluno. O horário reservado é tratado como um compromisso. Portanto, por favor, agende apenas se tiver certeza de que poderá comparecer.

**E-mail:** <arthur.viaro@usp.br><br>
**Atendimento:** Sala 230, FEA 2
</div>

## Bibliografia

- Material preparado pelo Prof. Danilo Souza para a disciplina: [https://danilosouza-usp.github.io/eae1106/](https://danilosouza-usp.github.io/eae1106/)
- Downey, A. B. (2016). *Pense em Python: Pense como um Cientista da Computação*. O'Reilly, 2ª edição
- Guttag, J. (2021). *Introduction to Computation and Programming Using Python: With Application to Computational Modeling and Understanding Data*. The MIT Press, 3ª edição.
- McKinney, W. (2018). *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*. O'Reilly, 2ª edição.
- T. J. Sargent e J. Stachurski. "Python Programming for Economics and Finance". [https://python-programming.quantecon.org/intro.html](https://python-programming.quantecon.org/intro.html)

## Material do Curso

*Links serão adicionados conforme disponibilização.*

### Notebooks

- [Aula 01: Introdução]()
- [Aula 02: Fundamentos de Computação]()

### Listas de Exercícios

*As listas devem ser entregues através do Moodle.*

- [Lista 1](): Entrega xx/xx, às 23h59
